- .gitignore
- README.md
- app/index.js
- scripts/gencerts.sh
user can deploy opentmi server using secure http (https) by create certification files in subfolder `sslcerts` and  giving `--https` -options when startin server.
> Https support

- package.json
at the moment only tests require it, but it will be needed also in implementation side so that why I added it to direct dependency..
> add missing dep: bluebird

- app/routes/groups.js
- package.json
**READY**
NO
get rid of node-testify-mongoose because it has Private Data Disclosure - not open enough for this project. It was used in groups before but now replaced with same approach than other routes.
> get rid of node-restify-mongoose

- app/controllers/index.js
- app/routes/testcases.js
**READY**
Testcases cannot be updated through API, this pr fixes that bug.
Bug was caused by testcase router extracting testcase id parameter with name "testcase". This caused the default controller to not find the mentioned parameter in the update function and thus leading to errors.
Solution, fix router to extract testcase id parameter as "Testcase".
* controllers/index.js
* routes/testcases.js
> Testcase route update failing - fix

- package.json
**READY**
NO
it should be user responsibility to select which `NODE_ENV` to be used so removed it from package.json scripts..
> remove NODE_ENV selection from package.json

- app/models/extends/file.js
- app/models/results.js
**READY**
This pr fixes the issue with server crashing if result with empty data is posted.
Root cause: path module trying to concat a string and undefined sha1, which causes an error.
* models/extends/file.js
* models/results.js
> Bugfix for posting results with empty data

- app/tools/logger.js
- package.json
- test/tests_unittests/addons/index.js
- test/tests_unittests/addons/mocking/addon-mock-files.json
**READY**
NO
This pr updates how winston is initialized and especially how daily-logger is handled. Fixes the not working daily file rotation.
Secondary problem arose from daily logger trying to open a log file while mock-fs was running a mocked file system. This causes tests to fail, not always, but too often.
This pr also fixes the secondary issue around addon tests.
* tools/logger.js
> Daily log rotation bugfix

- Gruntfile.js
- config/env/test.js
- scripts/dbrestore.sh
**READY**
This pr aims to separate the testing environment from development environment. This allows for example tests that expect filedb to contain specific logs.
Since fiddling with grunt tasks is time consuming, this pr also changes the dbrestore.sh to work on both linux and windows without modifications. 
* gruntfile.js
* scripts
> Change tests node_env to test

- app/controllers/users.js
- test/tests_api/users.js
**IN DEVELOPMENT**
NO
Give empty object when get user settings even there is no settings stored under that namespace
> empty object when get non existing user settings

- app/controllers/admin.js
- app/tools/update/gitUpdater.js
- app/tools/update/npm.js
- app/tools/update/updater.js
- test/tests_api/app.init.js
- test/tests_unittests/tools/update/gitUpdater.js
- test/tests_unittests/tools/update/npm.js
- test/tests_unittests/tools/update/updater.js
**READY**
NO
commit id was not properly in API when requesting version.
added option to fetch just brief information (`npm version`) because `npm list` takes quite long time. deep version details can be fetched by query parameter `deep=true`
#94
> fix git commitId in version API response

- app/master.js
- test/tests_unittests/master.js
**READY**
NO
* This changes stats structure a bit to support more details clearer way
adds
* add more jsdoc for function
* update unit tests
#94 (extracted from here)
> rework master getStats()

- app/controllers/socketio.js
- app/index.js
- app/routes/index.js
- app/routes/socketio.js
- doc/APIs/authentication.md
- doc/APIs/readme.md
- doc/APIs/socketio.md
- package.json
- test/tests_api/socketio.js
**READY**
NO
rework socketio step better - it will be more in use in future so this is prepare PR for it.
Now user have to use query token to use socketio connections (implemented in opentmi-jsclient).
This also brings simple `whoami` socketio API to give user related information from DB.
#94 (extracted from here)
> rework socketio to use authentication

- app/controllers/index.js
- test/tests_api/results.js
**READY**
NO
revert find query to use callback because mongoose-query is not tested enough with promises.
#115 PR breaks this in first place (was landed to v0.5.0)
> revert find with type count back as a object like it was originally.

- app/models/results.js
**READY**
NO
Fixes case: `Cannot read property 'sut' of undefined"` when uploading result where build exists already.
> Hotfix result storing with existing build

- app/controllers/index.js
- app/db.js
- app/models/group.js
- app/models/plugins/isempty.js
- app/models/user.js
- app/routes/groups.js
- app/routes/users.js
- test/tests_api/results.js
> replace obsoleting mongoose calls

- .circleci/config.yml
**READY**
YES, new recommended node.js version
Upgrade node.js to 8.11.4 in CI
> upgrade node.js to 8.11.4

- app/tools/logger.js
**READY**
YES: touch master `MasterLogger` -implementation. Should work still without master update because WorkerLogger manage conversion also.
winston-express calls logger.log with `{level, message, meta}` instead of `level, message, meta` causing unexpected exception
> fix express-winston logger wrapping

- app/tools/config.js
**READY**
NO
#200 causes unexpected exception in node.js 6.x when config.json does not exists - because fs.copyFileSync coming in node.js 8.x. Switches to use fs.copySync instead.
> use fs.copySync instead - copyFileSync does not exists until node 8.x

- app/models/event.js
- package-lock.json
- package.json
- test/tests_api/events.js
**READY**
NO
Add traceid field for events model and index for it with msgid.
**NOTE**: traceid + msgid is unique if traceid exists. (require mongodb 3.2<)
#233 Extending events model
> add traceid for event model

- app/tools/logger.js
**READY**
YES
timestamp was not printed to logs properly. This fixes it but require master restart
**NOTE:** require service break to get working, but can be included even without restart.
> print proper timestamp in winston logger

- README.md
- app/controllers/emailer.js
- app/controllers/users.js
- app/index.js
- app/models/user.js
- app/routes/users.js
- config.example.json
- doc/APIs/user.md
- package-lock.json
- package.json
- test/unittests/controller/users.js
**READY**
NO
added 2 more APIs' for recover user email address
```
POST /api/v0/password/forgot  (payload: {email: <email>})
POST /api/v0/password/change (payload {token: <token>, password: <new-password>})
```
require smtp configurations to `config.json` as `"smtp"` keyword. configurations are bypassed to https://nodemailer.com/smtp/ transport configurations. See example configuration from [`config.example.json`](https://github.com/OpenTMI/opentmi/blob/master/config.example.json).
> add password recovery mechanism

- README.md
- app/addons/addon.js
- app/index.js
- app/tools/config.js
- app/tools/logger.js
- package-lock.json
**READY**
NO
* allow to suppress file logging using "--log null" -arguments
* reduce file logging amount to 3 days
* fix --autoInstallAddonDeps option
> tuning arguments and logger

- test/tests_api/events.js
- test/tests_api/items.js
- test/tests_api/loans.js
- test/tests_api/results.js
**READY**
NO
There was bug in mockgoose earlier which forces to skip certain tests. PR try to bring test back on track.
> activate skipped api item tests

- package-lock.json
- package.json
**READY**
NO
This fixes mapReduce and allows to use more options for queries, like `to` (timeout).
> update mongoose-query to ^v0.6.0

- app/controllers/index.js
- app/controllers/resources.js
- app/models/resource.js
- app/models/testcase.js
- test/tests_api/events.js
- test/tests_api/resource.js
**READY**
NO
Testcase and Resource models has conversion for _id field and in API there was visible `id`. This PR consolidate id handling so that its same for each models - just mongo default `_id`.
-> Rename testcase and resource identify field: `id` -> `_id` that was done in toJSON transformer.
**NOTE:**
* **This is breaking change** - resource and test case identified field is changed from `id` -> `_id`.
* Does not affect opentmi-pyclient neither opentmi-jsclient because they expects already that `_id` field exists in these documents.
> Consolidate document id field

- .circleci/config.yml
**READY**
NO
node v6 is obsoleted, no need to test it anymore
> drop node v6 from CI

- .gitmodules
**READY**
YES.  
default_gui is not included in git anymore and need to deploy separately.
This just simplify server side and allows more flexible way to deploy actual UI. 
Sometimes default_gui is not even needed or is replaced with custom one.
Anyway, default_gui can be deployed separately when needed just by dropping it under `app/addons/` folder.
> remove default_gui submodule

- app/models/results.js
- test/tests_api/mocking/mockResult.json
- test/tests_api/results.js
**READY**
NO
* mostly result related internal refactoring (es6 async/await usage)
* Add `platform: {type: String},` for duts object
* `exec.dut` -path is now virtual, virtual value is coming from from `exec.duts.0` object.
* link test case to result object when `tcid` exists but tcRef does not
* drop empty default values
> Result model tune

- app/controllers/index.js
- test/unittests/controller/resources.js
NO
allow to select (`f=<field>`), populate (`p=[<field>]|[<json>]`)
and use timeout (`to=<number>`) when get single document. Note same format than mongoose-query has which is used for many document search.
default timeout for single document get is 5s
> improve single document get API
