- app/addons/index.js
- package.json
update async dep, and log errors during addon loading
> update async and log exceptions when addon loading fails

- Gruntfile.js
- README.md
- app/controllers/index.js
- app/db.js
- app/index.js
- app/models/plugins/resource-allocator.js
- app/routes/groups.js
- app/routes/users.js
- config/config.js
- config/express.js
- test/app.init.js
- test/resource.js
```
$ npm start -- -h
Usage: npm start -- (options)
Options:
--listen, -l   set binding interface             [string] [default: "0.0.0.0"]
--port         set listen port                      [required] [default: 3000]
--cfg, -c      Select configuration (development,test,production)
[string] [default: "development"]
--verbose, -v  verbose level                                           [count]
--silent, -s   Silent mode                                    [default: false]
```
> added more cli parameters and handle more carefully them

- app/addons/index.js
- app/models/resource.js
- package.json
> small improvements

- app/models/build.js
reorganize builds schema and added several more properties for it
> update build schema

- app/models/results.js
> default hw result type

- Gruntfile.js
Added functionality for grunt tests to include test cases from add-ons also.
> Grunt update

- app/index.js
- app/routes/addons.js
node gives warning because of upper case global object so fix those..
> use lower case global object

- .gitignore
- app/controllers/builds.js
- app/controllers/results.js
- app/models/build.js
- app/models/results.js
- app/routes/builds.js
- app/routes/results.js
- config/config.js
- config/env/development.js
- config/env/production.js
- config/env/test.js
- package.json
new routes:
`/api/v0/results/:Result/builds/:Index/download`
when uploaded build contains `data`, it will be stored to local fs / mondogb depend on configuration.
Also file sha1 will be stored so that it will be unique
`/api/v0/duts/builds/:Build/files/:Index/download`
when result is uploaded with  `exec.sut.buildSha1`,. tmi backend search related build file and attach that as reference if found.
where `Index` is file index in document. download start downloading that file.
Client doesn't need to know where file is physical located. TMI will handle it.
`filedb = process.env.FILE_DB || './data',`
`./data` is gitignored
> Build files

- app/index.js
- app/models/build.js
allow to use base64 encoded data
> Build base64

- app/index.js
- config/express.js
move body-parser json limits to right place
> Update express bodyParser

- app/addons/index.js
- app/index.js
- config/middlewares/authorization.js
- package.json
remove underscore dep and tune addon loading and logging a bit
> Tune addon loading

- app/models/build.js
this should fix issue where filedb didn't work correctly with multiple files
> fix build filedb

- app/models/results.js
format any json object, e.g.
```
{ "flash_duration": 10}
```
> possibility to link test execution profiling

- .gitignore
- app/models/build.js
- app/models/file.js
- app/models/results.js
- app/tools/checksum.js
- app/tools/filedb.js
- app/tools/index.js
* move file schema to own file and re-use it for result logs
* move general functions under tools -folder
> refactor filedb handling

- app/controllers/authentication.js
- app/index.js
- config/middlewares/authorization.js
**READY**
Increases and clarifies the amount of logging done during the authentication process on multiple logging levels e.q. info, debug and verbose.
app/controllers/authentication.js
> Auth logging update

- app/controllers/authentication.js
- app/db.js
- app/express.js
- app/index.js
- app/models/file.js
- app/routes/default.js
- app/routes/items.js
- app/routes/loans.js
- app/routes/settings.js
- app/routes/users.js
- app/tools/filedb.js
- config/index.js
- config/middlewares/authorization.js
- test/tests_api/app.init.js
- test/tests_api/builds.js
- test/tests_api/items.js
- test/tests_api/loans.js
- test/tests_api/resource.js
- test/tests_api/users.js
**READY**
Refactored nconf access. Configuration now accessible from a singleton block that handles the nconf initialization.
controllers, authorization and just about everything.
> redirected nconf calls to more controllable singleton package.

- Gruntfile.js
- app/controllers/authentication.js
- app/db.js
- app/express.js
- app/index.js
- app/models/file.js
- app/routes/default.js
- app/routes/items.js
- app/routes/loans.js
- app/routes/settings.js
- app/routes/users.js
- app/tools/filedb.js
- config/index.js
- config/middlewares/authorization.js
- package.json
- test/tests_api/app.init.js
- test/tests_api/builds.js
- test/tests_api/items.js
- test/tests_api/loans.js
- test/tests_api/resource.js
- test/tests_api/users.js
- test/tests_unittests/tools/filedb.js
**READY**
This pr adds unittests to the rewritten filedb, also contains changes necessary to make filedb pass the said tests.
branch | PR
------ | ------
filedb-rewrite | [https://github.com/OpenTMI/opentmi/pull/43]()
* app/tools/filedb.js
* models/file.js
* tests/unittests/
> Filedb rewrite tests

- app/models/extends/file.js
- app/models/results.js
**READY**
NO
add couple more indexes for major properties
> add some major indexes to speed up performance

- README.md
**READY**
NO
There was obsolete status badges in readme - updated them and add couple more
> update readme status badges

- app/routes/users.js
**READY**
NO
Addon authentication route for OAuth 2 redirect variable capturing.
* app/routes/users.js
> Auth redirect route

- scripts/aws_backup.sh
**READY**
Take a database dump from mongodb and push it to AWS S3 bucket.
> MongoDB AWS backup script

- package.json
> update grunt-exec dev dep

- app/models/build.js
- app/models/results.js
- app/tools/filedb.js
**READY**
NO
Fixed result files storage - seems that fileProvider was not defined right way and added some more traces
> Fix file storage when result is uploaded to DB

- app/master.js
- test/tests_unittests/master.js
**READY**
NO
If we receive unexpected message do not throw - instead just log error
> do not raise when unexpected message arrived

- app/db.js
- app/tools/logger.js
**READY**
This pr removes own db reconnect implementations which collide with autoReconnect that mongoose provides. Provides more controlled handling of database connection outage.
* app/db.js
> More controlled db reconnect

- app/models/results.js
**READY**
This pr extends results models exec verdict enum options. "skip" is now a valid verdict for results.
Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.
* models/results.js
> Allow skip as verdict for result

- .dockerignore
- Dockerfile
- README.md
- config/env/development.js
- doc/docker.md
- package-lock.json
**READY**
NO
Initial support for docker container. This PR brings also `package-lock.json` -file to repository.
> Initial docker support

- package.json
**READY**
NO
Bumb version number
> bumb version number

- app/addons/sample/package.json
**READY**
NO
just eslint fixes
> eslint fixes for sample package.json

- app/index.js
- app/master.js
- test/tests_unittests/master.js
**READY**
NO
handle cluster workers killing and worker exit more robust way
#94 #100
> more careful exiting

- package.json
**READY**
NO
This is major version from mocha so update it in separate PR
> update dev dep mocha

- package.json
**READY**
NO
Bumb patch version number
> bumb version

- app/controllers/authentication.js
- config/middlewares/authorization.js
**READY**
NO
refactoring createJWT to use promises and integrate little more details to it
#94 (extracted from here)
> refactoring createJWT to use promises

- app/controllers/clusters.js
- app/controllers/common.js
- app/routes/admin.js
- app/routes/cluster.js
**READY**
NO
If cluster is not in use return "not found" 404 response when calling some cluster related API
#116 (worker part for this)
#94  (extracted from here)
> create static Promise function for stats reading from master

- app/tools/logger.js
**READY**
NO
Fixes log dir creation
#111
> tried to call mkdir with filename instead of dir

- app/models/index.js
- app/models/testcase.js
- app/routes/users.js
**READY**
NO
if ensureIndexes fails print log reason about it and give short instructions what to do. Continue running server anyway. This is more or less workaround to continue server running.
#115 - this PR causes that if ensureIndexes fails it stop the server right way.
> ignore even ensureIndexes fails

- app/controllers/apikeys.js
- app/controllers/authentication.js
- app/controllers/index.js
- app/controllers/loans.js
- app/routes/admin.js
- config/middlewares/authorization.js
- package.json
- test/tests_api/builds.js
- test/tests_api/items.js
- test/tests_api/loans.js
- test/tests_api/results.js
- test/tests_api/users.js
- test/tests_cluster/app.init.js
- test/tests_unittests/test-controller-loans.js
**READY**
NO
Seems that there was multiple places where token sub -property was in use previously.
This PR replace all those sub with _id  and increase test coverage related token usage.
#114  breaks this in first place
> fix jwt token usage

- .eslintrc.json
- app/models/extends/file.js
- app/models/results.js
- package.json
- test/tests_unittests/tools/filedb.js
This reverts commit 833c42fd3c710947028ae3a0f142f64bb5bed212.
This seems not to work yet.
#108
> Revert "Update eslint-config-airbnb to the latest version 🚀 (#108)"

- package.json
**READY**
NO
That fixes leanQuery with flatten option and other small bugs.
> update mongoose-query -dependency

- package.json
**READY**
NO
Updarte mongoose-query dependency. There is multiple fixes which affect to opentmi API's positive way. E.g. aggregate query should work now through rest API.
Closes #132
> fix(package): update mongoose-query to version 0.5.1

- app/tools/validators.js
**READY**
NO
Fixes resource tags and apps validator.
> fixing validators for tags and apps in resources

- package.json
> update socket.io-adapter-mongo to 2.0.1

- package.json
> update supersgent to 3.8.1

- app/models/results.js
**READY**
NO
Dut provider for results
> add dut provider for result model

- package-lock.json
- package.json
**READY**
NO
Update should dependency
> update should -module to 13.2.1

- .gitignore
- app/addons/addon.js
- config/index.js
**READY**
NO
addon can now use more easily mongoose and addon related settings.
added also option to read configurations from settings.json file from app root folder.
https://github.com/OpenTMI/opentmi-addon/pull/3
> share mongoose and addon settings to addon instance

- app/db.js
- package.json
**READY**
NO
Update mongoose to 5.0.6 and fixes couple 5.x related breaks
> Mongoose 5.0.6

- app/db.js
- app/models/index.js
**READY**
NO
Clean up more mongoose obsoleted warnings
> fixes more obsoleted mongo calls

- app/models/plugins/isempty.js
- package-lock.json
- test/tests_unittests/controllers/builds.js
- test/tests_unittests/controllers/results.js
- test/tests_unittests/controllers/schemas.js
- test/tests_unittests/mongomock.js
- test/tests_unittests/test-controller-campaigns.js
- test/tests_unittests/test-controller-groups.js
- test/tests_unittests/test-controller-index.js
- test/tests_unittests/test-controller-items.js
- test/tests_unittests/test-controller-loans.js
- test/tests_unittests/test-controller-resources.js
- test/tests_unittests/test-controller-testcases.js
- test/tests_unittests/test-controller-users.js
**READY**
NO
Fix and activating more tests
> activate more tests

- .circleci/config.yml
- README.md
**READY**
YES, new mongodb recommendation
Update latest mongodb 4.1.2 in CI
> upgrade mongodb to 4.1.2 in CI

- package-lock.json
- package.json
> fix one potential security vulnerability in one dependencies

- Gruntfile.js
- README.md
- app/server.js
- app/tools/config.js
- config.example.json
- package.json
**READY**
NO
FIX: Configurations did not allow to overwrite args defaults from file
> Cfg fixing

- app/express.js
- app/tools/logger.js
**READY**
NO
* add timestamp
* restrict DailyRotateFile max size (100m) and file count (10d)
* add pid to log filename
> improving logging

- app/master.js
- app/tools/logger.js
**READY**
NO
* assign log level if unknown
* catch errors from worker message handlers
workaround for #205 - avoid crashing even unexpected exception happens in worker message handler.
> Small robustneus improvements

- app/controllers/authentication.js
- app/controllers/index.js
- app/controllers/users.js
- app/models/user.js
- app/routes/error.js
- app/routes/index.js
- app/routes/users.js
- config.example.json
- test/tests_api/events.js
- test/tests_api/users.js
- test/tests_unittests/test-controller-users.js
**READY**
NO
Extracted some changes from #209 
* more promise flows in User model
* more tests for User model
* improve traces
> small improvements around

- .circleci/config.yml
- Gruntfile.js
**READY**
NO
Circleci job was configured wrong and test required mongorestore did not work as expected.
Reason why tests passes earlier was that authentication middlewares did not work properly and allow to use some API's without right permissions. #209 will fix that. This PR just brings mongorestore back in track.
> fix mongorestore step

- package-lock.json
- package.json
> Greenkeeper/eslint plugin chai expect 2.0.1

- app/controllers/passport/github.js
- app/models/user.js
**READY**
NO
Allow to login without group. Improve traces
#209
> fix github login when user does not belong to admin group

- package-lock.json
- package.json
> Greenkeeper/mongoose 5.3.6

- package-lock.json
- package.json
> Greenkeeper/winston daily rotate file 3.3.5

- package-lock.json
- package.json
> Greenkeeper/mongoose 5.3.11

- package-lock.json
- package.json
> Greenkeeper/mongoose 5.3.14

- app/controllers/events.js
- doc/APIs/resources.md
- test/tests_api/resource.js
- test/tests_api/tools/helpers.js
**READY**
NO
fixed bug in `resources/:id/utilization` and improve robustneus for failure cases
> more robust resource handler for events and more regression tests

- package-lock.json
- package.json
> update patch rel number

- app/controllers/events.js
- app/controllers/index.js
- app/models/event.js
- test/tests_api/events.js
- test/unittests/controller/events.js
- test/unittests/controller/groups.js
- test/unittests/helpers.js
**READY**
NO
* add facility result
* validation that reference is required for some cases.
* add duration (Number) and spare (Mixed) properties
> Extending events model

- package.json
Closes #230
**READY**
NO
see title
> fix(package): update mongoose-schema-jsonschema to version 1.2.1

- package-lock.json
- package.json
> Greenkeeper/mongoose 5.4.4

- package-lock.json
- package.json
> Greenkeeper/winston daily rotate file 3.6.0

- package.json
> chore(package): update mongoose to version 5.4.14

- Dockerfile
> use node 8 in dockerfile

- package-lock.json
- package.json
> Greenkeeper/chokidar 3.0.2

- package-lock.json
- package.json
> Greenkeeper/async 3.1.0

- package-lock.json
- package.json
> Greenkeeper/winston daily rotate file 3.10.0

- package-lock.json
- package.json
> fs-extra 8.1.0

- package-lock.json
- package.json
> Greenkeeper/mongoose 5.6.5

- .circleci/config.yml
- README.md
- app/models/extends/file.js
- package-lock.json
- package.json
- test/unittests/tools/filedb.js
- test/utils/mongomock.js
**READY**
YES
* Drop node@8 support and test node@12
* Replace obsoleted and problematic mockgoose with mongodb-memory-server
> Update node requirements

- Dockerfile
- Gruntfile.js
- index.js
- package.json
* update version number to 0.9.0
* start single instance by default
* upgrade dockerfile node version 8 -> 12
> prepare next version

- app/db.js
- app/models/index.js
- app/models/plugins/resource-allocator.js
- app/tools/config.js
**READY**
NO
* mongoose useCreateIndex: true
* drop invalid logging step
* do not autoinstall deps by default
> fix startup issues

- Dockerfile
- app/config.defaults.json
- app/controllers/emailer.js
- app/index.js
- app/tools/config.js
- app/tools/update/npmUpdater.js
- app/tools/update/updater.js
- docker-compose.yml
- package-lock.json
- package.json
- test/unittests/tools/update/gitUpdater.js
**READY**
NO
Introduce docker-compose file.
optimize Dockerfile and use node alpine version. Small fixes for exceptions and teardown.
> Docker compose

- .circleci/config.yml
- .gitignore
- app/controllers/authentication.js
- app/controllers/passport/github.js
- app/controllers/socketio.js
- app/routes/default.js
- app/routes/middlewares/authorization.js
- app/routes/socketio.js
- app/routes/users.js
- app/tools/SocketLoggerTransport.js
- package.json
- test/tests_api/socketio.js
**READY**
NO
Introduce logs -sio room and improve logging
> improvements

- .circleci/config.yml
Add more node.js@v14 to CI and drop latest since dependency not working
> add node@14 version to CI

- .github/workflows/docker.yml
- .github/workflows/push.yml
Build docker image for each PR and master merge + releases.
push with tag `opentmi/opentmi:latest` when merging to master and with `opentmi/opentmi:<version>` when release
> docker workflow

- Dockerfile
NO
Update node@14 for docker image
> update node@14 for docker

- package.json
> versio number updated

- app/controllers/index.js
- app/models/item.js
- app/models/resource.js
- app/tools/validators.js
NO
Add more fields to resource model:
* `location.rack`
* `location.bed`
* `location.slot`
* `hw. meta_data` (string dictionary)
* `shield.rf`
Link existing Item object to resource while saving resource in both direction. resource `item.model` is same as `item.name`
> link resources and items

- app/models/loan.js
NO
Ensure that loaning unique resource is not duplicate loaned
> Loan api tuning

- app/models/resource.js
NO
add sparse unique `barcode` field for resource model
> add unique barcode for resource model

- app/controllers/loans.js
NO
ensure that item is not returned already
> check if already returned

- Dockerfile
- app/tools/healthcheck.js
- docker-compose.yml
- package.json
NO
Drop ui build deps from Docker image and add simple healthcheck for docker usage
> optimize dockerile and avoid install ui build deps
